/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lesports.bole.api.vo;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 数据抓取来源
 * 
 */
public enum TBoleSource implements org.apache.thrift.TEnum {
  ZHIBO8(1),
  QQ(2),
  SINA(3);

  private final int value;

  private TBoleSource(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TBoleSource findByValue(int value) { 
    switch (value) {
      case 1:
        return ZHIBO8;
      case 2:
        return QQ;
      case 3:
        return SINA;
      default:
        return null;
    }
  }
}
