/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lesports.bole.api.vo;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TBoleStatus implements org.apache.thrift.TEnum {
  IMPORTED(0),
  CREATED(1),
  CONFIRMED(2),
  INVALID(3),
  EXPORTED(4),
  ATTACHED(5);

  private final int value;

  private TBoleStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TBoleStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return IMPORTED;
      case 1:
        return CREATED;
      case 2:
        return CONFIRMED;
      case 3:
        return INVALID;
      case 4:
        return EXPORTED;
      case 5:
        return ATTACHED;
      default:
        return null;
    }
  }
}
