/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lesports.bole.api.vo;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 直播类型
 * 
 */
public enum TBoleLiveType implements org.apache.thrift.TEnum {
  VIDEO(0),
  IMAGE_TEXT(1);

  private final int value;

  private TBoleLiveType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TBoleLiveType findByValue(int value) { 
    switch (value) {
      case 0:
        return VIDEO;
      case 1:
        return IMAGE_TEXT;
      default:
        return null;
    }
  }
}
